# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
TWITTER_CONSUMER_KEY: hIl8qNe1VqxKJuxHhWoA
TWITTER_CONSUMER_SECRET: iQxdv9Ak6T9fM8DtvdGAdGZGDqfvyiTiCXbPaXI0U8Y
TWITTER_ACCESS_TOKEN: 1944743442-3pV23TQz68mT0GeyoINA6HDwRoe78UvWwLRLWuY
TWITTER_ACCESS_SECRET: w6hMGXVwNKCjL60jhEDXJs1nzhMP0r5Rmsxoa7wSRc
